# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

target 'FritzImageLabelingDemo' do
  use_frameworks!

  pod 'Fritz', '6.1.1'
  pod 'Fritz/VisionLabelModel/Fast'

end
