# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

target 'FritzSkyReplacementDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FritzSkyReplacementDemo
  pod 'Fritz', '6.1.1'
  pod 'Fritz/VisionSegmentationModel/Sky/Fast'

end
