# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

target 'FritzImageSegmentationDemo' do
  use_frameworks!

  pod 'Fritz', '6.0.0'
  pod 'Fritz/VisionSegmentationModel/People/Fast'
end
